apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orca-secrets
  namespace: orca
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: replace-with-store
    kind: ClusterSecretStore
  target:
    name: orca-secrets
  data:
    - secretKey: api-key
      remoteRef:
        key: orca/api-key
    - secretKey: neo4j-password
      remoteRef:
        key: orca/neo4j-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orca-platform-secrets
  namespace: orca
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: replace-with-store
    kind: ClusterSecretStore
  target:
    name: orca-platform-secrets
  data:
    - secretKey: neo4j-password
      remoteRef:
        key: orca/platform/neo4j-password
    - secretKey: temporal-postgres-user
      remoteRef:
        key: orca/platform/temporal-postgres-user
    - secretKey: temporal-postgres-password
      remoteRef:
        key: orca/platform/temporal-postgres-password
    - secretKey: temporal-postgres-db
      remoteRef:
        key: orca/platform/temporal-postgres-db
