apiVersion: v1
kind: Secret
metadata:
  name: orca-platform-secrets
  namespace: orca
type: Opaque
stringData:
  neo4j-password: replace-me
  temporal-postgres-user: temporal
  temporal-postgres-password: replace-me
  temporal-postgres-db: temporal
