apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orca
resources:
  - ../namespace.yaml
  - ../platform-secrets.example.yaml
  - redis.yaml
  - weaviate.yaml
  - neo4j.yaml
  - temporal-postgres.yaml
  - temporal.yaml
