apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend
  namespace: orca
spec:
  selector:
    app: orca-temporal
  ports:
    - name: frontend
      port: 7233
      targetPort: 7233
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orca-temporal
  namespace: orca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orca-temporal
  template:
    metadata:
      labels:
        app: orca-temporal
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.28.0
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orca-platform-secrets
                  key: temporal-postgres-user
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: orca-platform-secrets
                  key: temporal-postgres-password
            - name: POSTGRES_SEEDS
              value: temporal-postgresql
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: config/dynamicconfig/docker.yaml
          readinessProbe:
            tcpSocket:
              port: 7233
          livenessProbe:
            tcpSocket:
              port: 7233
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
